# Generated by Django 6.0.5 on 2026-06-15 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('event_type', models.CharField(choices=[('wedding', 'Mariage'), ('birthday', 'Anniversaire'), ('corporate', 'Corporate'), ('graduation', 'Remise de diplôme'), ('other', 'Autre')], max_length=20, verbose_name="type d'événement")),
                ('event_type_other', models.CharField(blank=True, max_length=100, verbose_name='autre type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='heure')),
                ('location', models.CharField(max_length=500, verbose_name='lieu')),
                ('google_maps_link', models.URLField(blank=True, verbose_name='lien Google Maps')),
                ('dress_code', models.CharField(blank=True, max_length=200, verbose_name='code vestimentaire')),
                ('drink_options', models.JSONField(default=list, verbose_name='options de boissons')),
                ('reminder_message', models.TextField(blank=True, verbose_name='message de rappel')),
                ('sender_email', models.EmailField(default='noreply@kbfeven.com', max_length=254, verbose_name='email expéditeur')),
                ('rsvp_token', models.CharField(blank=True, max_length=36, unique=True, verbose_name='token RSVP')),
                ('coorganizer_token', models.CharField(blank=True, max_length=36, unique=True, verbose_name='token co-organisateur')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_paid', models.BooleanField(default=False, verbose_name='payé')),
                ('max_guests_allowed', models.PositiveIntegerField(default=400, verbose_name="nombre max d'invités")),
                ('max_collaborators_allowed', models.PositiveIntegerField(default=5, verbose_name='nombre max de co-organisateurs')),
                ('main_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to=settings.AUTH_USER_MODEL, verbose_name='organisateur principal')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_token', models.CharField(max_length=50, unique=True, verbose_name="token d'invitation")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté')], default='pending', max_length=20, verbose_name='statut')),
                ('can_scan', models.BooleanField(default=False, verbose_name='peut scanner')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='invité le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepté le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='events.event', verbose_name='événement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'co-organisateur',
                'verbose_name_plural': 'co-organisateurs',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='numéro')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('capacity', models.PositiveIntegerField(default=8, verbose_name='capacité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='events.event', verbose_name='table')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['number'],
                'unique_together': {('event', 'number')},
            },
        ),
    ]
