# Generated by Django 6.0.5 on 2026-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coorganizer_short_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='code court co-organisateur'),
        ),
    ]
