# Generated by Django 6.0.5 on 2026-06-05 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('will_attend', models.BooleanField(default=True, verbose_name='sera présent(e)')),
                ('number_of_guests', models.PositiveIntegerField(default=1, verbose_name='nombre de personnes')),
                ('drink_choice', models.CharField(blank=True, choices=[('vin', 'Vin'), ('biere', 'Bière'), ('soft', 'Soft'), ('other', 'Autre')], max_length=20, verbose_name='choix de boisson')),
                ('drink_other', models.CharField(blank=True, max_length=100, verbose_name='autre boisson')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='végétarien/végétalien')),
                ('special_notes', models.TextField(blank=True, verbose_name='notes spéciales')),
                ('verification_status', models.CharField(choices=[('verified', 'Vérifié - Invité officiel'), ('unverified', 'Non vérifié - Personne non invitée')], default='unverified', help_text='Vérifié = la personne était dans la liste des invités pré-enregistrés', max_length=20, verbose_name='statut de vérification')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='soumis le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='rappel envoyé')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='rappel envoyé le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': "réponse d'invité",
                'verbose_name_plural': 'réponses des invités',
                'ordering': ['-submitted_at'],
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='InvitedGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_guests', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'invité pré-enregistré',
                'verbose_name_plural': 'invités pré-enregistrés',
                'ordering': ['name'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
