# Generated by Django 6.0.5 on 2026-06-05 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('drink_choice', models.CharField(blank=True, max_length=200, null=True, verbose_name='choix de boisson')),
                ('drink_other', models.TextField(blank=True, null=True, verbose_name='autre boisson')),
                ('is_accompanied', models.BooleanField(default=False, verbose_name='accompagné')),
                ('companion_drink_choice', models.CharField(blank=True, max_length=200, null=True, verbose_name='choix boisson accompagnant')),
                ('companion_drink_other', models.TextField(blank=True, null=True, verbose_name='autre boisson accompagnant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('declined', 'Décliné')], default='pending', max_length=20, verbose_name='statut')),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token unique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'invité',
                'verbose_name_plural': 'invités',
                'ordering': ['-created_at'],
            },
        ),
    ]
