# Generated by Django 6.0.5 on 2026-06-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_coorganizer_short_code'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedguest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_guests', to='events.table', verbose_name='table assignée'),
        ),
    ]
