# Generated by Django 6.0.5 on 2026-06-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_add_coorganizer_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeveragePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100, verbose_name='nom de la boisson')),
                ('pack_quantity', models.PositiveIntegerField(default=12, verbose_name='quantité par pack')),
                ('pack_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prix par pack')),
                ('unit_type', models.CharField(blank=True, help_text='ex: bouteille, canette', max_length=50, verbose_name="type d'unité")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beverage_packs', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'pack de boisson',
                'verbose_name_plural': 'packs de boissons',
                'ordering': ['drink_name'],
                'unique_together': {('event', 'drink_name')},
            },
        ),
    ]
